# Nome do banco
# AUTO_SERVER permite reabrir o mesmo arquivo H2 por outra JVM durante o desenvolvimento.
spring.datasource.url=jdbc:h2:file:./clinicadb;AUTO_SERVER=TRUE

# Prefixo base da API
server.servlet.context-path=/api

# Driver do H2
spring.datasource.driver-class-name=org.h2.Driver

# Usuário e senha
spring.datasource.username=sa
spring.datasource.password=

# Atualiza as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Ativa o console web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostra o SQL gerado pelo JPA no terminal
spring.jpa.show-sql=true

# Caminho do Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
